CREATE DATABASE AVA1;
USE AVA1;

CREATE TABLE usuario(
    nome VARCHAR(50) NOT NULL,
    usuario VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    senha VARCHAR(32) NOT NULL, 
    CONSTRAINT PRIMARY KEY(usuario, senha)
);